# Generated by Django 5.2.8 on 2025-11-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0004_alter_item_category_alter_item_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orderrr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
