# Generated by Django 5.2.8 on 2025-11-24 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0005_orderrr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orderrr',
        ),
    ]
